config/routes.rb
Megaupload::Application.routes.draw do
  resources :up_files

  resources :events

  resources :users

	root :to => 'home#index', :as => :home
	
	match 'logout' => 'home#logout', :as => :logout
	
	match 'facebook' => 'oauth#new_facebook'

	match 'facebook_login' => 'oauth#facebook_login'
	
	match 'upload' => 'up_files#upload', :as => :upload

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :end_date, :file_type, :name, :user_id, :guest_list
	
	belongs_to :user
	has_many :up_files
	
	validates :name,
		:length => { :minimum => 1 }
	
	validate :validate_future_end_date
	
	def validate_future_end_date
		if end_date
			if end_date < Time.now
			errors.add(:end_date, ": El evento debe terminar en el futuro") if end_date < Time.now
			end
		end

	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
	if session[:user_id]
		@events = Event.find_all_by_user_id(session[:user_id])

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @events }
		end
	else
		redirect_to home_path
	end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

	if @event.user_id == session[:user_id]
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @event }
		end
	else
		redirect_to home_path
	end
  end

  # GET /events/new
  # GET /events/new.json
  def new
	if session[:user_id]
		@event = Event.new
		@event.user_id = session[:user_id]
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @event }
		end
	else
		redirect_to home_path
	end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
	if session[:user_id]
		@event = Event.new(params[:event])
		@event.user_id = session[:user_id]

		respond_to do |format|
			if @event.save
				@event.guest_list.split(';').each do |g|
					@up_file = UpFile.new()
					@up_file.mail = g.delete(' ')
					@up_file.event_id = @event.id
					if @up_file.save
						begin
							InvitationMailer.invitation_mail(@up_file, @event).deliver
						rescue Exception => e
						end
					end
				end
				#redirect_to home_path
				format.html { redirect_to @event, notice: 'Evento fue creado exitosamente.' }
				format.json { render json: @event, status: :created, location: @event }
			else
				format.html { render action: "new" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	else
		redirect_to home_path
	end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

	if session[:user_id] == @event.user_id
		respond_to do |format|
			if @event.update_attributes(params[:event])
				format.html { redirect_to @event, notice: 'Evento fue actualizado.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	else
		redirect_to home_path
	end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
	if @event.user_id == session[:user_id]
		@event.destroy
	end
	
	redirect_to home_path
	
    #respond_to do |format|
    #  format.html { redirect_to events_url }
    #  format.json { head :no_content }
    #end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<center><% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> evitó el guardado de este evento:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %></center>
<%= form_for(@event, :html => { :class => "create_new_event"} ) do |f| %>
  <center><div class="field">
    <%= f.text_field :name, :class=>'input-block-level', :placeholder=>'Nombre de Evento'%>
  </div>
  <div class="field">
    <%= f.label 'Fecha Final' %><br />
    <!-- Calendar-->
  <div id="datetimepicker1" class="input-append date">
    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="event[end_date]"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
</div>
    <!-- Calendar end -->

  </div>
  <div class="field">
    <%= f.label "Tipo de Archivo" %><br />
    <%= f.text_field :file_type %>
  </div>
<div class="field">
    <textarea class="input-block-level" cols="40" id="guest-text-box" name="event[guest_list]" placeholder="Invitados (Separados por ;)" rows="5"></textarea>
  </div>
  <div class="actions">
    <%= f.submit 'Crear Evento', :class => 'btn btn-large btn-primary' %>
  </div></center>
<% end %>

app/views/events/_index.html.erb
<div class="new_event"><center><h1 id="new_event_heading" class="form-signin-heading">Tus Eventos</h1><a id="new_event_button" class="btn btn-primary btn-large" href="/events/new">+ |  Crear Nuevo Evento</a></center></div>
<% if @events.empty? %>
<center><p> &iexcl;No tienes eventos! </p></center>
<% else %>
<div class="event-table">
<table class="table table-bordered table-hover">
  <tr>
    <th>Nombre</th>
    <th>Fecha L&iacute;mite</th>
    <th>Tipo de Archivo</th>
    <th>Invitados</th>
    <th>Opciones</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, event %></td>
    <td><%= event.end_date %></td>
     <td><%= event.file_type %></td>
    <% if event.up_files.empty? %>
    <td>0</td>
    <% else %>
    <td><%= event.up_files.count %></td>
    <% end %>
    <td><%= link_to 'Ver', event %> - <%= link_to 'Editar', edit_event_path(event) %> - <%= link_to 'Eliminar', event, method: :delete, data: { confirm: '¿Seguro que desea eliminar el evento?' } %></td>
  </tr>
<% end %>
</table>
</div>
<% end %>
<br />

app/views/events/edit.html.erb
<center><h1 class="form-signin-heading">Editando Evento</h1></center>

<%= render 'form' %>

app/views/events/index.html.erb
<%= render 'events/index' %>

app/views/events/new.html.erb
<center><h1 class="form-signin-heading">Nuevo Evento</h1></center>

<%= render 'form' %>

app/views/events/show.html.erb
<center><p id="notice"><%= notice %></p></center>

<div class="event_view_header"><center><h1 id="event-name-heading" class="form-signin-heading"><%= @event.name %></h1>(<%= link_to 'Editar', edit_event_path(@event) %>)</center></div>
<center>
<p>
  <b>Fecha L&iacute;mite:</b>
  <%= @event.end_date %>
</p>

<p>
  <b>Tipo de Archivo:</b>
  <%= @event.file_type %>
</p>
</center>
<!-- Table of users go here -->
<% if @event.up_files.empty? %>
<center><p> &iexcl;No tienes invitados! </p></center>
<% else %>
<div class="guests-table">
<table class="table table-bordered table-hover">
  <tr>
    <th>Email</th>
    <th>Archivo</th>
  </tr>

<% @event.up_files.each do |up_file| %>
  <tr>
    <td><%= up_file.mail %></td>
    <% if !up_file.upload_file_file_size %>
    <td><p> &iexcl;Sin archivo! </p></td>
    <% else %>
    <td><%= link_to 'Archivo', up_file.upload_file.url %></td>
    <% end %>   </tr>
<% end %>
</table>
</div>
<% end %>