config/routes.rb
Megaupload::Application.routes.draw do
  resources :up_files

  resources :events

  resources :users

	root :to => 'home#index', :as => :home
	
	match 'logout' => 'home#logout', :as => :logout
	
	match 'facebook' => 'oauth#new_facebook'

	match 'facebook_login' => 'oauth#facebook_login'
	
	match 'upload' => 'up_files#upload', :as => :upload

end

app/models/up_file.rb
class UpFile < ActiveRecord::Base
  	attr_accessible :Url, :mail, :event_id, :upload_file
  
  	belongs_to :event
  
	def gen_token
		token = ""
		mail.chars.to_a.each do |c|
			val = c.ord #- 96
			if val < 10
				token = token + "00" + val.to_s
			else
				if val < 100
					token = token + "0" + val.to_s
				else
					token = token + val.to_s
				end
			end
		end
		token = token + event_id.to_s
		srand token.to_i
		token = token + rand(token.to_i).to_s
		return token
	end

	has_attached_file :upload_file
	
  
end

app/controllers/up_files_controller.rb
class UpFilesController < ApplicationController
  # GET /up_files
  # GET /up_files.json
  def index
	if session[:user_id]
		@up_files = UpFile.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @up_files }
		end
	else
		redirect_to home_path
	end
  end

  # GET /up_files/1
  # GET /up_files/1.json
  def show
    @up_file = UpFile.find(params[:id])
	if @up_file.event.user.id == session[:user_id]
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @up_file }
		end
	else
		redirect_to home_path
	end
  end

  # GET /up_files/new
  # GET /up_files/new.json
  def new
    @up_file = UpFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @up_file }
    end
  end

  # GET /up_files/1/edit
  def edit
    @up_file = UpFile.find(params[:id])
  end

  # POST /up_files
  # POST /up_files.json
  def create
    @up_file = UpFile.new(params[:up_file])

    respond_to do |format|
      if @up_file.save
        format.html { redirect_to @up_file, notice: 'Archivo de subida creado con &eacute;xito.' }
        format.json { render json: @up_file, status: :created, location: @up_file }
      else
        format.html { render action: "new" }
        format.json { render json: @up_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /up_files/1
  # PUT /up_files/1.json
  def update
    @up_file = UpFile.find(params[:id])

      if @up_file.update_attributes(params[:up_file])
        redirect_to home_path
      else
	respond_to do |format|
        	format.html { render action: "edit" }
        	format.json { render json: @up_file.errors, status: :unprocessable_entity }
      	end
     end
  end

  # DELETE /up_files/1
  # DELETE /up_files/1.json
  def destroy
    @up_file = UpFile.find(params[:id])
    @up_file.destroy

    respond_to do |format|
      format.html { redirect_to up_files_url }
      format.json { head :no_content }
    end
  end
  
	def upload
		if !params[:mail] or !params[:event] or !params[:token]
			flash[:error] = "Link equivocado."
			redirect_to home_path
		else
			if !UpFile.exists?(:mail=> params[:mail], :event_id => params[:event])
				flash[:error] = "Link equivocado."
				redirect_to home_path
			else
				@up_file = UpFile.find_by_mail_and_event_id(params[:mail],params[:event])
				if @up_file.gen_token == params[:token]
					render 'upload.html'
				else
					flash[:error] = "Link equivocado."
					redirect_to home_path
				end
			end
		end
	end
  

  
end

app/helpers/up_files_helper.rb
module UpFilesHelper
end

app/views/up_files/_form.html.erb
<%= form_for @up_file, :html => { :multipart => true } do |f| %>
  <% if @up_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@up_file.errors.count, "error") %> evitó a este archivo ser guardado.:</h2>

      <ul>
      <% @up_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Url %><br />
    <%= f.text_field :Url %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :upload_file %><br />
    <%= f.file_field :upload_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/up_files/edit.html.erb
<h1>Editing up_file</h1>

<%= render 'form' %>

<%= link_to 'Ver', @up_file %> |
<%= link_to 'Atr&aacute;s', up_files_path %>

app/views/up_files/index.html.erb
<h1>Listing up_files</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Email</th>
	<th>Token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @up_files.each do |up_file| %>
  <tr>
    <td><%= up_file.Url %></td>
    <td><%= up_file.mail %></td>
	<td><%= up_file.gen_token.to_s %></td>
    <td><%= link_to 'Ver', up_file %></td>
    <td><%= link_to 'Editar', edit_up_file_path(up_file) %></td>
    <td><%= link_to 'Eliminar', up_file, method: :delete, data: { confirm: '&iquest;Seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuebo Archivo de subida', new_up_file_path %>

app/views/up_files/new.html.erb
<h1>Nuevo up_file</h1>

<%= render 'form' %>

<%= link_to 'Atr&aacute;s', up_files_path %>

app/views/up_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @up_file.Url %>
</p>

<p>
  <b>Email:</b>
  <%= @up_file.mail %>
</p>

<p>
  <b>URL de subida de archivo:</b>
  <%= image_tag @up_file.upload_file.url %>
</p>

<p>
  <b>Subir Archivo:</b>
  <%= @up_file.upload_file.url %>
</p>


<%= link_to 'Editar', edit_up_file_path(@up_file) %> |
<%= link_to 'Atr&aactue;s', up_files_path %>

app/views/up_files/upload.html.erb
<center><% if @up_file.upload_file_file_size %>

	<h1>&iexcl;Su archivo ya ha sido subido!</h1>
	<p>Por favor contacte a <%= @up_file.event.user.mail %> para ayuda.</p>

<% else %>

	<h1 id="new_event_heading" class="form-signin-heading">Suba su archivo</h1>
	
	<%= form_for @up_file, :html => { :multipart => true } do |f| %>
	
		<div class="field">
			<%= f.label :upload_file %><br />
			<%= f.file_field :upload_file %>
		</div>
	
		<div class="actions">
			<%= f.submit %>
		</div>
	
	<% end %>
	
<% end %></center>