config/routes.rb
Megaupload::Application.routes.draw do
  resources :up_files

  resources :events

  resources :users

	root :to => 'home#index', :as => :home
	
	match 'logout' => 'home#logout', :as => :logout
	
	match 'facebook' => 'oauth#new_facebook'

	match 'facebook_login' => 'oauth#facebook_login'
	
	match 'upload' => 'up_files#upload', :as => :upload

end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MegaUP" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
	  <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="wrapper">
    <!-- 1 nav bar goes here -->
    <div class="header">
      <div class ="logo"><%= link_to image_tag("Logo-Small.png"), home_path  %></div>
		<% if session[:user_id] %>
      <div class="logout_header"><%= link_to "Logout", logout_path %></div>
		<% else %>
			<div class="signs_header"><%= link_to "Identificarse", home_path %> - 
      <%= link_to 'Registrarse', new_user_path %></div>
		<% end %>		
	</div>
    <div class="content" id="main" role="main">
              <%= yield %>
              <div class="push"></div>
    </div> <!--! end of #main -->
</div>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag 'bootstrap-datetimepicker.min' %>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      
    });
  });
</script>
  </body>
</html>